#pragma once

#undef TAPPING_TERM
#define TAPPING_TERM 170

#define IGNORE_MOD_TAP_INTERRUPT

#define TAPPING_FORCE_HOLD

#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT TAPPING_TERM
#define AUTO_SHIFT_NO_SETUP

#define COMBO_COUNT 8
#define COMBO_TERM 30
